### ISSUE TITLE
Incident is not reported in cockpit

### ISSUE THREAD

**Issue by OHUser** [camunda-consulting/on-demand-call-activity#54]
In case of failure from downstream application, we are throwing an exception, which will be caught by camunda and incident will be reported in cockpit. 
We are getting exception as "ENGINE-14006 Exception while executing job 4ac7648c-3eeb-11eb-a300-0a580afe2d36 : processDefinitionId is null". For the job, processDefinitionId is set as null. The process instance is stuck in running state only. Attaching the full logs.

**JobId :** 4ac7648c-3eeb-11eb-a300-0a580afe2d36
**TraceId :** a4315a54a33fc971

**Stacktrace :** 
{"mdc":{"traceId":"a4315a54a33fc971","spanId":"21bb89260eee2217","spanExportable":"false","X-Span-Export":"false","X-B3-SpanId":"21bb89260eee2217","X-B3-TraceId":"a4315a54a33fc971"},"timestamp":"2020-12-16 06:28:56.771","level":"WARN","logger":"org.camunda.bpm.engine.jobexecutor","message":"ENGINE-14006 Exception while executing job 4ac7648c-3eeb-11eb-a300-0a580afe2d36: ","exception":"\norg.camunda.bpm.engine.exception.NullValueException: Invalid process definition id: processDefinitionId is null\n\tat sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat org.camunda.bpm.engine.impl.util.EnsureUtil.generateException(EnsureUtil.java:394)\n\tat org.camunda.bpm.engine.impl.util.EnsureUtil.ensureNotNull(EnsureUtil.java:55)\n\tat org.camunda.bpm.engine.impl.util.EnsureUtil.ensureNotNull(EnsureUtil.java:50)\n\tat org.camunda.bpm.engine.impl.persistence.deploy.cache.ProcessDefinitionCache.checkInvalidDefinitionId(ProcessDefinitionCache.java:42)\n\tat org.camunda.bpm.engine.impl.persistence.deploy.cache.ResourceDefinitionCache.findDeployedDefinitionById(ResourceDefinitionCache.java:48)\n\tat org.camunda.bpm.engine.impl.persistence.deploy.cache.DeploymentCache.findDeployedProcessDefinitionById(DeploymentCache.java:77)\n\tat org.camunda.bpm.engine.impl.cmd.DefaultJobRetryCmd.getCurrentActivity(DefaultJobRetryCmd.java:131)\n\tat org.camunda.bpm.engine.impl.cmd.DefaultJobRetryCmd.execute(DefaultJobRetryCmd.java:63)\n\tat org.camunda.bpm.engine.impl.jobexecutor.FailedJobListener$1.execute(FailedJobListener.java:64)\n\tat org.camunda.bpm.engine.impl.jobexecutor.FailedJobListener$1.execute(FailedJobListener.java:54)\n\tat org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:28)\n\tat org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:110)\n\tat org.camunda.bpm.engine.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:46)\n\tat org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)\n\tat org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:44)\n\tat org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70)\n\tat org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)\n\tat org.camunda.bpm.engine.impl.jobexecutor.FailedJobListener.execute(FailedJobListener.java:54)\n\tat org.camunda.bpm.engine.impl.jobexecutor.FailedJobListener.execute(FailedJobListener.java:32)\n\tat org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:28)\n\tat org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:110)\n\tat org.camunda.bpm.engine.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:46)\n\tat org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)\n\tat org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:44)\n\tat org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70)\n\tat org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)\n\tat org.camunda.bpm.engine.impl.jobexecutor.ExecuteJobHelper.callFailedJobListenerWithRetries(ExecuteJobHelper.java:113)\n\tat org.camunda.bpm.engine.impl.jobexecutor.ExecuteJobHelper.invokeJobListener(ExecuteJobHelper.java:94)\n\tat org.camunda.bpm.engine.impl.jobexecutor.ExecuteJobHelper.executeJob(ExecuteJobHelper.java:75)\n\tat org.camunda.bpm.engine.impl.jobexecutor.ExecuteJobsRunnable.executeJob(ExecuteJobsRunnable.java:110)\n\tat org.camunda.bpm.engine.impl.jobexecutor.ExecuteJobsRunnable.run(ExecuteJobsRunnable.java:71)\n\tat org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:67)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n\n","thread_id":"camundaTaskExecutor-24"}

**Comment by OHUser** [comment]
[orchestrator_logs.zip](https://github.com/camunda-consulting/on-demand-call-activity/files/5701355/orchestrator_logs.zip)

**Comment by falko** [comment]
- Saw in DB that process_def_id is null
- Next steps:
  - create a support issue
  - In parallel test
  - Without asynchronous service task
  - Without On-demand Call Activity Plugin

**Comment by falko** [comment]
NFT lab was not able to reproduce the issue. Support issue has been created: https://jira.camunda.com/browse/SUPPORT-9491

**Comment by falko** [comment]
Since this is worked on via SUPPORT-9491, this issue is closed.

**Comment by falko** [comment]
Notes from today's meeting: Last night's tests reported that this might be happening again. More investigation is needed.
